"""Atualizando guia

Revision ID: 0849c5a5c073
Revises: 17139439b474
Create Date: 2025-03-29 12:45:48.957963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0849c5a5c073'
down_revision = '17139439b474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.alter_column('pago',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.alter_column('pago',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
