"""Atualizando os relacionamentos da tabela encaminhametos

Revision ID: 0cae3d769c65
Revises: f4de37f8ab57
Create Date: 2025-05-07 20:42:43.227975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cae3d769c65'
down_revision = 'f4de37f8ab57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situacao_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_encaminhamento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_encaminhamentos_tipo_encaminhamento_id', 'tipo_encaminhamento', ['tipo_encaminhamento_id'], ['id'])
        batch_op.create_foreign_key('fk_encaminhamentos_situacao_id', 'situacao', ['situacao_id'], ['id'])
        batch_op.drop_column('situacao')
        batch_op.drop_column('tipo_encaminhamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_encaminhamento', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('situacao', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_encaminhamentos_tipo_encaminhamento_id', type_='foreignkey')
        batch_op.drop_constraint('fk_encaminhamentos_situacao_id', type_='foreignkey')
        batch_op.drop_column('tipo_encaminhamento_id')
        batch_op.drop_column('situacao_id')

    # ### end Alembic commands ###
