"""Criação do estado civil

Revision ID: 168ae1f1acc4
Revises: 8aaf86029ac1
Create Date: 2025-07-09 20:11:45.225985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168ae1f1acc4'
down_revision = '8aaf86029ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_civis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estados_civis')
    # ### end Alembic commands ###
