"""Retirando o unique do email do cliente

Revision ID: 17139439b474
Revises: 6de111323bbc
Create Date: 2025-03-23 15:56:09.363860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17139439b474'
down_revision = '6de111323bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index('ix_clientes_email')
        batch_op.create_index(batch_op.f('ix_clientes_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_email'))
        batch_op.create_index('ix_clientes_email', ['email'], unique=1)

    # ### end Alembic commands ###
