"""Migração Inicial

Revision ID: 1ef746db9cfb
Revises: 
Create Date: 2025-05-07 17:42:53.873679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef746db9cfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condicao_habitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escolaridade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grau_parentesco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodo_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('juros', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('especialidade', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('situacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_moradia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('renda_familiar', sa.Float(), nullable=False),
    sa.Column('bairro', sa.String(length=255), nullable=True),
    sa.Column('canal_divulgacao', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('cpf_responsavel', sa.String(length=14), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('numero_cs', sa.String(length=20), nullable=True),
    sa.Column('despesa_mensal', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('fone_contato', sa.String(length=20), nullable=True),
    sa.Column('fone_pessoal', sa.String(length=20), nullable=True),
    sa.Column('nome_plano_saude', sa.String(length=255), nullable=True),
    sa.Column('plano_saude', sa.String(length=255), nullable=True),
    sa.Column('nome_responsavel', sa.String(length=255), nullable=True),
    sa.Column('possui_filhos', sa.String(length=255), nullable=True),
    sa.Column('numero_filhos', sa.Integer(), nullable=True),
    sa.Column('previdenciario', sa.String(length=255), nullable=True),
    sa.Column('profissao', sa.String(length=255), nullable=True),
    sa.Column('remuneracao', sa.Float(), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo_id', sa.Integer(), nullable=True),
    sa.Column('condicao_habitacao_id', sa.Integer(), nullable=True),
    sa.Column('tipo_moradia_id', sa.Integer(), nullable=True),
    sa.Column('tipo_transporte_id', sa.Integer(), nullable=True),
    sa.Column('escolaridade_id', sa.Integer(), nullable=True),
    sa.Column('grau_parentesco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condicao_habitacao_id'], ['condicao_habitacao.id'], ),
    sa.ForeignKeyConstraint(['escolaridade_id'], ['escolaridade.id'], ),
    sa.ForeignKeyConstraint(['grau_parentesco_id'], ['grau_parentesco.id'], ),
    sa.ForeignKeyConstraint(['sexo_id'], ['sexo.id'], ),
    sa.ForeignKeyConstraint(['tipo_moradia_id'], ['tipo_moradia.id'], ),
    sa.ForeignKeyConstraint(['tipo_transporte_id'], ['tipo_transporte.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('encaminhamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.Integer(), nullable=True),
    sa.Column('metodo_pagamento_id', sa.Integer(), nullable=True),
    sa.Column('situacao_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metodo_pagamento_id'], ['metodo_pagamento.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['situacao_id'], ['situacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guias')
    op.drop_table('encaminhamentos')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('tipo_transporte')
    op.drop_table('tipo_moradia')
    op.drop_table('situacao')
    op.drop_table('sexo')
    op.drop_table('profissionais')
    op.drop_table('metodo_pagamento')
    op.drop_table('grau_parentesco')
    op.drop_table('escolaridade')
    op.drop_table('condicao_habitacao')
    # ### end Alembic commands ###
