"""Atualizando a tabela de profissionais

Revision ID: 25f44e5f4c41
Revises: 1ef746db9cfb
Create Date: 2025-05-07 20:24:09.580822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f44e5f4c41'
down_revision = '1ef746db9cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=False))
        batch_op.add_column(sa.Column('data_nascimento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('banco', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('graduacao', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('issqn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fone_pessoal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fone_profissional', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('curriculum_lattes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dias_horas_disponiveis', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('endereco_profissional', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pix', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('registro_profissional', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rg', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('valor_minimo', sa.Float(), nullable=True))
        batch_op.create_unique_constraint('uq_profissionais_cpf', ['cpf'])
        batch_op.create_unique_constraint('uq_profissionais_rg', ['rg'])
        batch_op.drop_column('especialidade')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('especialidade', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('valor_minimo')
        batch_op.drop_column('rg')
        batch_op.drop_column('registro_profissional')
        batch_op.drop_column('pix')
        batch_op.drop_column('observacoes')
        batch_op.drop_column('estado')
        batch_op.drop_column('endereco_profissional')
        batch_op.drop_column('dias_horas_disponiveis')
        batch_op.drop_column('curriculum_lattes')
        batch_op.drop_column('fone_profissional')
        batch_op.drop_column('fone_pessoal')
        batch_op.drop_column('issqn')
        batch_op.drop_column('graduacao')
        batch_op.drop_column('complemento')
        batch_op.drop_column('cidade')
        batch_op.drop_column('cep')
        batch_op.drop_column('banco')
        batch_op.drop_column('bairro')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
