"""Atualizando a tabela de guias

Revision ID: 2af96127e8df
Revises: 37b04363c90c
Create Date: 2025-03-21 12:18:54.085710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af96127e8df'
down_revision = '37b04363c90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.drop_column('valor_total')

    # ### end Alembic commands ###
