"""Add coluna de data de cadastro

Revision ID: 2fe66341e47d
Revises: f3e98081b705
Create Date: 2025-06-21 01:39:54.582895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe66341e47d'
down_revision = 'f3e98081b705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###
