"""Criação inicial do banco

Revision ID: 37b04363c90c
Revises: 
Create Date: 2025-02-11 21:58:46.793891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b04363c90c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('renda_familiar', sa.Float(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('canal_divulgacao', sa.String(), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('condicao_habitacao', sa.String(), nullable=True),
    sa.Column('cpf_responsavel', sa.String(length=11), nullable=True),
    sa.Column('numero_cs', sa.String(), nullable=True),
    sa.Column('despesa_mensal', sa.Float(), nullable=True),
    sa.Column('escolaridade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('fone_contato', sa.String(), nullable=True),
    sa.Column('fone_pessoal', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('grau_parentesco', sa.String(), nullable=True),
    sa.Column('nome_plano_saude', sa.String(), nullable=True),
    sa.Column('nome_responsavel', sa.String(), nullable=True),
    sa.Column('numero_filhos', sa.Integer(), nullable=True),
    sa.Column('possui_filhos', sa.String(), nullable=True),
    sa.Column('plano_saude', sa.String(), nullable=True),
    sa.Column('previdenciario', sa.String(), nullable=True),
    sa.Column('profissao', sa.String(), nullable=True),
    sa.Column('remuneracao', sa.Float(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('tipo_moradia', sa.String(), nullable=True),
    sa.Column('transporte', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_nome'), ['nome'], unique=False)

    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('banco', sa.String(), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('graduacao', sa.String(), nullable=True),
    sa.Column('issqn', sa.String(), nullable=True),
    sa.Column('fone_pessoal', sa.String(), nullable=True),
    sa.Column('fone_profissional', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('curriculum_lattes', sa.String(), nullable=True),
    sa.Column('dias_horas_disponiveis', sa.String(), nullable=True),
    sa.Column('endereco_profissional', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('pix', sa.String(), nullable=True),
    sa.Column('registro_profissional', sa.String(), nullable=True),
    sa.Column('rg', sa.String(), nullable=True),
    sa.Column('valor_minimo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profissionais_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_profissionais_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_profissionais_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profissionais_nome'), ['nome'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_nome'), ['nome'], unique=False)

    op.create_table('encaminhamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.Integer(), nullable=True),
    sa.Column('convenio', sa.String(), nullable=True),
    sa.Column('dias_horas_atendimento', sa.String(), nullable=True),
    sa.Column('data_encaminhamento', sa.Date(), nullable=True),
    sa.Column('observacoes_gerais', sa.String(), nullable=True),
    sa.Column('queixa', sa.String(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.Column('tipo_encaminhamento', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encaminhamentos_id'), ['id'], unique=False)

    op.create_table('guias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.Integer(), nullable=True),
    sa.Column('data_original', sa.Date(), nullable=True),
    sa.Column('hora_emissao', sa.String(), nullable=True),
    sa.Column('observacoes_gerais', sa.String(), nullable=True),
    sa.Column('quantidade_emissoes', sa.Integer(), nullable=True),
    sa.Column('tipo_pagamento', sa.String(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guias_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guias_id'))

    op.drop_table('guias')
    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encaminhamentos_id'))

    op.drop_table('encaminhamentos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_nome'))
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profissionais_nome'))
        batch_op.drop_index(batch_op.f('ix_profissionais_id'))
        batch_op.drop_index(batch_op.f('ix_profissionais_email'))
        batch_op.drop_index(batch_op.f('ix_profissionais_cpf'))

    op.drop_table('profissionais')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_nome'))
        batch_op.drop_index(batch_op.f('ix_clientes_id'))
        batch_op.drop_index(batch_op.f('ix_clientes_email'))
        batch_op.drop_index(batch_op.f('ix_clientes_cpf'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
