"""Atualizando o cadastro de cliente

Revision ID: 4bafab28690d
Revises: 2af96127e8df
Create Date: 2025-03-22 15:36:14.019105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bafab28690d'
down_revision = '2af96127e8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complemento', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('complemento')

    # ### end Alembic commands ###
