"""Atualizando tabela de clientes 2

Revision ID: 4bfe01a957f7
Revises: ea66968dfb64
Create Date: 2025-05-03 20:14:17.024149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfe01a957f7'
down_revision = 'ea66968dfb64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renda_familiar', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('bairro', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('canal_divulgacao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cpf_responsavel', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero_cs', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('despesa_mensal', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fone_contato', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fone_pessoal', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('grau_parentesco', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nome_plano_saude', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('plano_saude', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nome_responsavel', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('possui_filhos', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero_filhos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('previdenciario', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profissao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('remuneracao', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('saldo', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('idade')
        batch_op.drop_column('saldo')
        batch_op.drop_column('rg')
        batch_op.drop_column('remuneracao')
        batch_op.drop_column('profissao')
        batch_op.drop_column('previdenciario')
        batch_op.drop_column('numero_filhos')
        batch_op.drop_column('possui_filhos')
        batch_op.drop_column('nome_responsavel')
        batch_op.drop_column('plano_saude')
        batch_op.drop_column('nome_plano_saude')
        batch_op.drop_column('grau_parentesco')
        batch_op.drop_column('fone_pessoal')
        batch_op.drop_column('fone_contato')
        batch_op.drop_column('endereco')
        batch_op.drop_column('estado')
        batch_op.drop_column('despesa_mensal')
        batch_op.drop_column('numero_cs')
        batch_op.drop_column('complemento')
        batch_op.drop_column('cpf_responsavel')
        batch_op.drop_column('cidade')
        batch_op.drop_column('cep')
        batch_op.drop_column('canal_divulgacao')
        batch_op.drop_column('bairro')
        batch_op.drop_column('renda_familiar')

    # ### end Alembic commands ###
