"""Atualizando a tabela de profissional

Revision ID: 649c5f0a99ad
Revises: 4bafab28690d
Create Date: 2025-03-22 15:45:23.472779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649c5f0a99ad'
down_revision = '4bafab28690d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complemento', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_column('complemento')

    # ### end Alembic commands ###
