"""Atualizando a tabela de cliente

Revision ID: 6de111323bbc
Revises: 649c5f0a99ad
Create Date: 2025-03-22 16:03:24.321715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de111323bbc'
down_revision = '649c5f0a99ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('idade')

    # ### end Alembic commands ###
