"""Mudei o nome da data de cadastro do usuário

Revision ID: 8aaf86029ac1
Revises: c6ff3a7c86b7
Create Date: 2025-07-09 20:07:31.704610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aaf86029ac1'
down_revision = 'c6ff3a7c86b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###
