"""Atualizando coluna 2

Revision ID: 951dd606602a
Revises: c8ba3a441de8
Create Date: 2025-01-27 16:46:53.779416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951dd606602a'
down_revision = 'c8ba3a441de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_activo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_activo', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
