"""Criação de função

Revision ID: a6d7f2c10495
Revises: cc19d2f2b1d7
Create Date: 2025-06-07 16:12:45.612530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d7f2c10495'
down_revision = 'cc19d2f2b1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###
