"""adicionando coluna na tb cliente

Revision ID: b11369aeb9b7
Revises: c8dca41739cd
Create Date: 2025-02-03 12:57:18.951904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11369aeb9b7'
down_revision = 'c8dca41739cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('possui_filhos', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('possui_filhos')

    # ### end Alembic commands ###
