"""Add coluna de usuario emitente

Revision ID: c6ff3a7c86b7
Revises: 2fe66341e47d
Create Date: 2025-06-21 02:06:08.805440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ff3a7c86b7'
down_revision = '2fe66341e47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_emitente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('usuario_emitente_id', 'usuarios', ['usuario_emitente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_emitente_id')

    # ### end Alembic commands ###
