"""Atualizando coluna

Revision ID: c8ba3a441de8
Revises: db68e6683d8a
Create Date: 2025-01-27 16:45:16.206670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ba3a441de8'
down_revision = 'db68e6683d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_activo', sa.Boolean(), nullable=True))
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_activo')

    # ### end Alembic commands ###
