"""Atualização de tabela cliente

Revision ID: c8dca41739cd
Revises: 67a5d88445a3
Create Date: 2025-02-02 18:06:47.274028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8dca41739cd'
down_revision = '67a5d88445a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
