"""Atualizando campo em encaminhamento

Revision ID: ea1cd8026111
Revises: 0cae3d769c65
Create Date: 2025-05-08 00:10:39.483915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1cd8026111'
down_revision = '0cae3d769c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.alter_column('data_encaminhamento',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.alter_column('data_encaminhamento',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
