"""Atualizando tabela de clientes

Revision ID: ea66968dfb64
Revises: 786ffeb6bd1a
Create Date: 2025-05-03 20:10:52.813883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea66968dfb64'
down_revision = '786ffeb6bd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=False))
        batch_op.add_column(sa.Column('data_nascimento', sa.DateTime(), nullable=True))
        # Nomeando a restrição UNIQUE para 'cpf'
        batch_op.create_unique_constraint('uq_cpf', ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        # Removendo a restrição UNIQUE nomeada 'uq_cpf'
        batch_op.drop_constraint('uq_cpf', type_='unique')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###

