"""Criação de função de usuario

Revision ID: f3e98081b705
Revises: a6d7f2c10495
Create Date: 2025-06-07 16:15:55.564361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e98081b705'
down_revision = 'a6d7f2c10495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
