"""Criação do estado civil 2

Revision ID: f43ae25e29ff
Revises: 168ae1f1acc4
Create Date: 2025-07-09 20:12:25.454173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43ae25e29ff'
down_revision = '168ae1f1acc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_civil_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_clientes_estado_civil_id',  # Nome da constraint
            'estados_civis',                # Tabela referenciada
            ['estado_civil_id'],            # Coluna local
            ['id']                          # Coluna da tabela referenciada
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clientes_estado_civil_id', type_='foreignkey')
        batch_op.drop_column('estado_civil_id')
    # ### end Alembic commands ###
