"""Atualizando a tabela de encaminhamentos

Revision ID: f4de37f8ab57
Revises: 25f44e5f4c41
Create Date: 2025-05-07 20:31:19.322798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4de37f8ab57'
down_revision = '25f44e5f4c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('convenio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dias_horas_atendimento', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('data_encaminhamento', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('observacoes_gerais', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('queixa', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('situacao', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tipo_encaminhamento', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=True))
        batch_op.drop_column('data')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('data', sa.DATETIME(), nullable=True))
        batch_op.drop_column('valor')
        batch_op.drop_column('tipo_encaminhamento')
        batch_op.drop_column('situacao')
        batch_op.drop_column('queixa')
        batch_op.drop_column('observacoes_gerais')
        batch_op.drop_column('data_encaminhamento')
        batch_op.drop_column('dias_horas_atendimento')
        batch_op.drop_column('convenio')

    # ### end Alembic commands ###
